/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LeiloesRouteImport } from './routes/leiloes'
import { Route as HallRouteImport } from './routes/hall'
import { Route as GravadorasRouteImport } from './routes/gravadoras'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AlbunsRouteImport } from './routes/albuns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistasIndexRouteImport } from './routes/artistas.index'
import { Route as PlaylistsNovaRouteImport } from './routes/playlists.nova'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as ArtistasNomeRouteImport } from './routes/artistas.$nome'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as AcoesTourRouteImport } from './routes/acoes.tour'
import { Route as AcoesCinemaRouteImport } from './routes/acoes.cinema'
import { Route as AcoesAlbumRouteImport } from './routes/acoes.album'
import { Route as ArtistasNomeProjetosRouteImport } from './routes/artistas.$nome.projetos'
import { Route as ArtistasNomeBensRouteImport } from './routes/artistas.$nome.bens'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LeiloesRoute = LeiloesRouteImport.update({
  id: '/leiloes',
  path: '/leiloes',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const GravadorasRoute = GravadorasRouteImport.update({
  id: '/gravadoras',
  path: '/gravadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbunsRoute = AlbunsRouteImport.update({
  id: '/albuns',
  path: '/albuns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasIndexRoute = ArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNovaRoute = PlaylistsNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PlaylistsRoute,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaylistsRoute,
} as any)
const ArtistasNomeRoute = ArtistasNomeRouteImport.update({
  id: '/artistas/$nome',
  path: '/artistas/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesTourRoute = AcoesTourRouteImport.update({
  id: '/acoes/tour',
  path: '/acoes/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesCinemaRoute = AcoesCinemaRouteImport.update({
  id: '/acoes/cinema',
  path: '/acoes/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesAlbumRoute = AcoesAlbumRouteImport.update({
  id: '/acoes/album',
  path: '/acoes/album',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasNomeProjetosRoute = ArtistasNomeProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => ArtistasNomeRoute,
} as any)
const ArtistasNomeBensRoute = ArtistasNomeBensRouteImport.update({
  id: '/bens',
  path: '/bens',
  getParentRoute: () => ArtistasNomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/gravadoras': typeof GravadorasRoute
  '/hall': typeof HallRoute
  '/leiloes': typeof LeiloesRoute
  '/market': typeof MarketRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/radar': typeof RadarRoute
  '/ranking': typeof RankingRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRoute
  '/artistas/$nome': typeof ArtistasNomeRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/gravadoras': typeof GravadorasRoute
  '/hall': typeof HallRoute
  '/leiloes': typeof LeiloesRoute
  '/market': typeof MarketRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/radar': typeof RadarRoute
  '/ranking': typeof RankingRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRoute
  '/artistas/$nome': typeof ArtistasNomeRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/artistas': typeof ArtistasIndexRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/gravadoras': typeof GravadorasRoute
  '/hall': typeof HallRoute
  '/leiloes': typeof LeiloesRoute
  '/market': typeof MarketRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/radar': typeof RadarRoute
  '/ranking': typeof RankingRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRoute
  '/artistas/$nome': typeof ArtistasNomeRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albuns'
    | '/charts'
    | '/gravadoras'
    | '/hall'
    | '/leiloes'
    | '/market'
    | '/playlists'
    | '/radar'
    | '/ranking'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/artistas/$nome'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/artistas/'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albuns'
    | '/charts'
    | '/gravadoras'
    | '/hall'
    | '/leiloes'
    | '/market'
    | '/playlists'
    | '/radar'
    | '/ranking'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/artistas/$nome'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/artistas'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
  id:
    | '__root__'
    | '/'
    | '/albuns'
    | '/charts'
    | '/gravadoras'
    | '/hall'
    | '/leiloes'
    | '/market'
    | '/playlists'
    | '/radar'
    | '/ranking'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/artistas/$nome'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/artistas/'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbunsRoute: typeof AlbunsRoute
  ChartsRoute: typeof ChartsRoute
  GravadorasRoute: typeof GravadorasRoute
  HallRoute: typeof HallRoute
  LeiloesRoute: typeof LeiloesRoute
  MarketRoute: typeof MarketRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  RadarRoute: typeof RadarRoute
  RankingRoute: typeof RankingRoute
  AcoesAlbumRoute: typeof AcoesAlbumRoute
  AcoesCinemaRoute: typeof AcoesCinemaRoute
  AcoesTourRoute: typeof AcoesTourRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistasNomeRoute: typeof ArtistasNomeRouteWithChildren
  ArtistasIndexRoute: typeof ArtistasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leiloes': {
      id: '/leiloes'
      path: '/leiloes'
      fullPath: '/leiloes'
      preLoaderRoute: typeof LeiloesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gravadoras': {
      id: '/gravadoras'
      path: '/gravadoras'
      fullPath: '/gravadoras'
      preLoaderRoute: typeof GravadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albuns': {
      id: '/albuns'
      path: '/albuns'
      fullPath: '/albuns'
      preLoaderRoute: typeof AlbunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/': {
      id: '/artistas/'
      path: '/artistas'
      fullPath: '/artistas/'
      preLoaderRoute: typeof ArtistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/nova': {
      id: '/playlists/nova'
      path: '/nova'
      fullPath: '/playlists/nova'
      preLoaderRoute: typeof PlaylistsNovaRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/artistas/$nome': {
      id: '/artistas/$nome'
      path: '/artistas/$nome'
      fullPath: '/artistas/$nome'
      preLoaderRoute: typeof ArtistasNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/tour': {
      id: '/acoes/tour'
      path: '/acoes/tour'
      fullPath: '/acoes/tour'
      preLoaderRoute: typeof AcoesTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/cinema': {
      id: '/acoes/cinema'
      path: '/acoes/cinema'
      fullPath: '/acoes/cinema'
      preLoaderRoute: typeof AcoesCinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/album': {
      id: '/acoes/album'
      path: '/acoes/album'
      fullPath: '/acoes/album'
      preLoaderRoute: typeof AcoesAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$nome/projetos': {
      id: '/artistas/$nome/projetos'
      path: '/projetos'
      fullPath: '/artistas/$nome/projetos'
      preLoaderRoute: typeof ArtistasNomeProjetosRouteImport
      parentRoute: typeof ArtistasNomeRoute
    }
    '/artistas/$nome/bens': {
      id: '/artistas/$nome/bens'
      path: '/bens'
      fullPath: '/artistas/$nome/bens'
      preLoaderRoute: typeof ArtistasNomeBensRouteImport
      parentRoute: typeof ArtistasNomeRoute
    }
  }
}

interface PlaylistsRouteChildren {
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  PlaylistsNovaRoute: typeof PlaylistsNovaRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsIdRoute: PlaylistsIdRoute,
  PlaylistsNovaRoute: PlaylistsNovaRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

interface ArtistasNomeRouteChildren {
  ArtistasNomeBensRoute: typeof ArtistasNomeBensRoute
  ArtistasNomeProjetosRoute: typeof ArtistasNomeProjetosRoute
}

const ArtistasNomeRouteChildren: ArtistasNomeRouteChildren = {
  ArtistasNomeBensRoute: ArtistasNomeBensRoute,
  ArtistasNomeProjetosRoute: ArtistasNomeProjetosRoute,
}

const ArtistasNomeRouteWithChildren = ArtistasNomeRoute._addFileChildren(
  ArtistasNomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbunsRoute: AlbunsRoute,
  ChartsRoute: ChartsRoute,
  GravadorasRoute: GravadorasRoute,
  HallRoute: HallRoute,
  LeiloesRoute: LeiloesRoute,
  MarketRoute: MarketRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  RadarRoute: RadarRoute,
  RankingRoute: RankingRoute,
  AcoesAlbumRoute: AcoesAlbumRoute,
  AcoesCinemaRoute: AcoesCinemaRoute,
  AcoesTourRoute: AcoesTourRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistasNomeRoute: ArtistasNomeRouteWithChildren,
  ArtistasIndexRoute: ArtistasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
